workflows:
  build_and_test:
    name: Build and Test Workflow
     scripts:
      - name: Install dependencies
        script: |
          ./gradlew dependencies
      - name: Run tests
        script: |
          ./gradlew test
      - name: Build APK
        script: |
          ./gradlew assembleRelease
    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab
    publishing:
      email:
        recipients:
          - billooko2@gmail.com

